version: "3.8"

services:
  backend:
    image: strapi/strapi:alpine
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend/app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./backend/data:/var/lib/postgresql/data

  frontend:
      build:
        context: ./frontend
        args:
          WORKDIR: $WORKDIR
          # API_URL: "http://localhost:$API_PORT" # 追加
      # コンテナで実行したいコマンド(CMD)
      command: npm run dev
      volumes:
        - "./frontend:/$WORKDIR"
      ports:
        - "$FRONT_PORT:3000"
      depends_on:
        - backend
